language: objective-c
osx_image: xcode11.5
sudo: false

env:
  matrix:
    - TRAVIS_NODE_VERSION: 10
    - TRAVIS_NODE_VERSION: 12

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install:
  - npm install -g cordova@latest
  - npm install
  - npm install -g codecov

script:
  - node --version
  - npm --version
  - npm test

after_script:
  - codecov
