language: objective-c
osx_image: xcode9.4
sudo: false

env:
  matrix:
    - TRAVIS_NODE_VERSION: '6'
    - TRAVIS_NODE_VERSION: '8'
    - TRAVIS_NODE_VERSION: '10'

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install:
  - npm install -g cordova@latest
  - npm install

script:
  - node --version
  - npm --version
  - npm test
