#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

#
# compile and launch a Cordova/iOS project to the simulator
#
function usage() {
    echo "Usage: $0"
    echo "      --clean    : clean before building"
    echo "      --debug    : use debug configuration (default)."
    echo "      --release  : use release configuration."
    echo "      --run      : run application after building"
    echo "      --fg       : run application in foreground after building"
}

CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd -P)
PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)

source "$CORDOVA_PATH/check_reqs"
cd "$PROJECT_PATH"

CONFIGURATION=Debug
CLEAN=
RUN=
while [[ $# -gt 0 ]]; do
    case "$1" in
        --debug) ;;
        --release) CONFIGURATION=Release;;
        --device) RUN=run ;; # ignored for osx
        --emulator) RUN=run ;; # ignored for osx
        --run) RUN=run ;; # ignored for osx
        --fg) RUN=fg;;
        --clean) CLEAN=clean;;
        *) echo "Unrecognized flag: $1"; usage; exit 2;;
    esac
    shift
done

xcodebuild \
    -xcconfig "$CORDOVA_PATH/build.xcconfig" \
    -project "$PROJECT_NAME.xcodeproj" \
    -target "$PROJECT_NAME" \
    -configuration "$CONFIGURATION" \
    $CLEAN build

if [ "$RUN" == "run" ]; then
    echo "Starting $PROJECT_NAME.app ..."
    exec "$PROJECT_PATH/build/$PROJECT_NAME.app/Contents/MacOS/$PROJECT_NAME" \
          > "$CORDOVA_PATH/console.log" 2>&1 &
elif [ "$RUN" == "fg" ]; then
    echo "Starting $PROJECT_NAME.app ..."
    exec "$PROJECT_PATH/build/$PROJECT_NAME.app/Contents/MacOS/$PROJECT_NAME"
fi